// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afmoxhllsyiqkhxhyxsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmbW94aGxsc3lpcWtoeGh5eHNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNzEyNzksImV4cCI6MjA1NDg0NzI3OX0.V7KwK4OQ72pv-iTy2Uz2o7TQw3z23keRMtqvYzqh_zI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);